name: Code Cov CI

on:
  push:
    branches: [develop]  # Trigger workflow on push to develop
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Set up MATLAB
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2022a  # Specify the MATLAB version

      # Install MOcov
      - name: Install MOcov
        run: |
          # Clone MOcov repository to /opt/MOcov
          sudo git clone https://github.com/MOxUnit/MOcov.git /opt/MOcov
          # Adjust permissions if necessary
          sudo chmod -R 755 /opt/MOcov

      # Run MATLAB tests with MOcov to generate coverage
      - name: Run MATLAB tests and generate MOcov coverage
        run: |
          matlab -batch "
            addpath('/opt/MOcov/MOcov'); % Add MOcov to MATLAB path
            test_suite = testsuite('test/test_myfunction.m');
            cov_data = mocov('-cover', 'src', '-tests', test_suite, '-quiet', '-cover_xml_file', 'coverage.xml');
          "

      # Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -f coverage.xml -F matlab
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
