name: Code Coverage

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2022a

      - name: Install MOcov
        run: |
          git clone https://github.com/MOxUnit/MOcov.git /opt/MOcov
          ls -la /opt/MOcov
          sudo chmod -R 755 /opt/MOcov

      - name: Create and run MATLAB script
        run: |
          echo 'addpath(genpath('\''/opt/MOcov'\''));
          addpath(genpath(''test''));
          addpath(genpath(''src''));
          mocov(''start'');
          try
              results = runtests(''test_myfunction.m'');
              assert(all([results.Passed]), ''Some tests failed'');
              mocov(''stop'');
              mocov(''-cover'', ''src'', ''-cover_xml_file'', ''coverage.xml'');
              exit(0);
          catch e
              disp(getReport(e));
              exit(1);
          end' > run_tests.m
          
          matlab -batch "run('run_tests.m')"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: matlab
          token: ${{ secrets.CODECOV_TOKEN }}
